CREATE TABLE IF NOT EXISTS students (
    student_id INTEGER PRIMARY KEY AUTOINCREMENT,
    school TEXT,
    sex TEXT,
    age INTEGER,
    address TEXT,
    famsize TEXT,
    Pstatus TEXT,
    Medu INTEGER,
    Fedu INTEGER,
    Mjob_id INTEGER,
    Fjob_id INTEGER,
    reason TEXT,
    guardian TEXT,
    traveltime INTEGER,
    studytime INTEGER,
    failures INTEGER,
    schoolsup TEXT,
    famsup TEXT,
    paid TEXT,
    activities TEXT,
    nursery TEXT,
    higher TEXT,
    internet TEXT,
    romantic TEXT,
    famrel INTEGER,
    freetime INTEGER,
    goout INTEGER,
    Dalc INTEGER,
    Walc INTEGER,
    health INTEGER,
    absences INTEGER,
    G1 INTEGER,
    G2 INTEGER,
    G3 INTEGER
);
